### ISSUE TITLE
Credit author of Icons

### ISSUE THREAD

**Issue by dronecoria** [LiquidGalaxyLAB/reforestation-assistant-simulator#15]
A link in the about page should be included with the reference of the author of icons:

I believe with just a text with link should be ok:

Icons of this app by freepik
https://www.freepik.com/

[license-47124069.pdf](https://github.com/LiquidGalaxyLAB/reforestation-assistant/files/6994243/license-47124069.pdf)

**Comment by KarinePistili** [comment]
Fixed on commit 6a0c302a958941ec89fd8b559a04be96f71e9198
