### ISSUE TITLE
Inconsistent List of species 

### ISSUE THREAD

**Issue by dronecoria** [LiquidGalaxyLAB/reforestation-assistant-simulator#17]
As you see in the picture there is loaded a list of species.
But when creating a new project the list of speceis  is empty.
![IMAGE 2021-08-16 20:06:18](https://user-images.githubusercontent.com/80221395/129609315-292ed92c-93a6-430f-9696-fe001cab6e3f.jpg)

![IMAGE 2021-08-16 20:06:40](https://user-images.githubusercontent.com/80221395/129609392-d6ff5e21-b59c-4e52-836f-3737be531c1e.jpg)

**Comment by KarinePistili** [comment]
You need to select the seeds on the project form before trying to use them on the map. The map shows only the seeds you want to use in this project, and not the whole database stored

**Comment by dronecoria** [comment]
OK, cool, thanks, I didn't realized that.
Maybe display a kindly reminder in case that there is 0 species added will help the user to understand.

"Please add species to the project to select them here."

Is strange that in the map allow to create a tree type called "none", and then when you try to select there is an empty list.

**Comment by KarinePistili** [comment]
Sure I'll add that to make it more clear

**Comment by KarinePistili** [comment]
Added in commit aecb71cbab940eca2564ffcfd54d1bc597ab94b8
