### ISSUE TITLE
Inconsistent perimeter in the map

### ISSUE THREAD

**Issue by dronecoria** [LiquidGalaxyLAB/reforestation-assistant-simulator#19]
As you see in the pictures, each time that the map is opened with the link "See Map" the perimeter is showed in a different way.
Is the default project named "Bosque mediterraneo"

![IMAGE 2021-08-16 20:17:11](https://user-images.githubusercontent.com/80221395/129610729-214a0d66-6e9d-4d25-8d61-389d3ac63e7e.jpg)

![IMAGE 2021-08-16 20:17:30](https://user-images.githubusercontent.com/80221395/129610771-0e1d2480-bb4a-42fa-9fc8-8e008e6be0a2.jpg)

**Comment by KarinePistili** [comment]
Fixed in commit 8f5a22f69e4a9ecc35eb6b39950f023339706c3d
