### ISSUE TITLE
Area parameter missing

### ISSUE THREAD

**Issue by dronecoria** [LiquidGalaxyLAB/reforestation-assistant-simulator#20]
One of the important parameters: area, is not showed in any moment in the app.

**Comment by KarinePistili** [comment]
I could not find a way to calculate the area of the polygon by only using the coordinates. This is why it is not displayed on the app.

**Comment by KarinePistili** [comment]
I added the area parameter to be an input for the user as I could not find the correct equation to display an aprox. value of area. Added in commit 2b2c0d8e29cae4dbea4c930cd3c2be70f29e1f5b
