### ISSUE TITLE
APK not available in folder

### ISSUE THREAD

**Issue by dronecoria** [LiquidGalaxyLAB/reforestation-assistant-simulator#21]
Apk file is not available in the linked folder in the readme:
https://github.com/LiquidGalaxyLAB/reforestation-assistant-simulator/tree/main/resources

**Comment by KarinePistili** [comment]
I'll be uploading it with this new version with the bugs fixed

**Comment by KarinePistili** [comment]
Last version uploaded on commit e1fd79852c10fa44810b1fb29b1a734dbfcc8ad3
